export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const MEMBERSHIP_START = "MEMBERSHIP_START";
export const MEMBERSHIP_SUCCESS = "MEMBERSHIP_SUCCESS";
export const MEMBERSHIP_FAIL = "MEMBERSHIP_FAIL";

export const AFFILIATE_START = "AFFILIATE_START";
export const AFFILIATE_FAIL = "AFFILIATE_FAIL";
export const AFFILIATE_SUCCESS = "AFFILIATE_SUCCESS";
export const AFFILIATE_GET_USERS_SUCCESS = "AFFILIATE_GET_USERS_SUCCESS";
